services:
  - type: web
    name: nexus-api
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_PORT
        value: "4000"
      - key: DATABASE_URL
        fromDatabase:
          name: nexus-db
          property: connectionString
      - key: DIRECT_URL
        fromDatabase:
          name: nexus-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false

databases:
  - name: nexus-db
    plan: free
    databaseName: nexus
    databaseUser: nexus_user
